#!/bin/bash

CAMERA_URL_CAPTURE="$1"
CAMERA_URL_STREAM="$2"
VIDEO_FILE_PATH="./camera/videos/"
IMAGE_FILE_PATH="./camera/images/"
MAX_UNREAD_FRAMES="300"
CAPTURE_TIMEOUT="1800"
FRAME_SLEEP="0.02"
STREAM_WIDTH="640"
STREAM_HEIGHT="360"
PURGE_DAYS="7"

mkdir -p $VIDEO_FILE_PATH
mkdir -p $IMAGE_FILE_PATH

python3 nvr_server.py $CAMERA_URL_CAPTURE $CAMERA_URL_STREAM $VIDEO_FILE_PATH $IMAGE_FILE_PATH $MAX_UNREAD_FRAMES $CAPTURE_TIMEOUT $FRAME_SLEEP $STREAM_WIDTH $STREAM_HEIGHT $PURGE_DAYS
