#!/bin/bash

CAMERA_URL_CAPTURE="$1"
CAMERA_URL_STREAM="$2"
FILE_PATH="./videos"
MAX_UNREAD_FRAMES="300"
CAPTURE_TIMEOUT="1800"
FRAME_SLEEP="0.02"
STREAM_WIDTH="640"
STREAM_HEIGHT="360"

python3 nvr_server.py $CAMERA_URL_CAPTURE $CAMERA_URL_STREAM $FILE_PATH $MAX_UNREAD_FRAMES $CAPTURE_TIMEOUT $FRAME_SLEEP $STREAM_WIDTH $STREAM_HEIGHT
